const imgArray = [
  {
    name: "El taller",
    description: "Imaginando cosas útiles!",
    class: "carousel-item active",
    source: "./images/Banner.png",
    altText: "WorkShop",
    buttonClass: "active",
    buttonAriaCurrent: 'aria-current="true"',
  },

  {
    name: "Maceteros",
    description: "Impregnados con aceite mineral",
    class: "carousel-item",
    source: "./images/Prod1.png",
    altText: "Macetero",
    buttonClass: "",
    buttonAriaCurrent: "",
  },

  {
    name: "Porta vaso con Código QR",
    description: "Grabado y corte laser",
    class: "carousel-item",
    source: "./images/Prod2.png",
    altText: "Porta vasos",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Porta vaso Logotipo",
    description: "Grabado y corte laser",
    class: "carousel-item",
    source: "./images/Prod3.png",
    altText: "Porta vaso",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Porta cepillos",
    description: "Impregnado de aceite mineral",
    class: "carousel-item",
    source: "./images/Prod4.png",
    altText: "Porta cepillos",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Porta cepillos",
    description: "Impregnado de aceite mineral",
    class: "carousel-item",
    source: "./images/Prod5.png",
    altText: "Porta cepillos",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Desayunador",
    description: "Superficie de porcelanato, canteado de bambú",
    class: "carousel-item",
    source: "./images/Prod6.png",
    altText: "Desayunador",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Lapicero",
    description: "Con huella de perrito",
    class: "carousel-item",
    source: "./images/Prod7.png",
    altText: "Lapicero",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Guacal",
    description: "Almacenamiento diverso con agarraderas de cuero",
    class: "carousel-item",
    source: "./images/Prod8.png",
    altText: "Guacal",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Guacal",
    description: "Almacenamiento diverso con agarraderas de cuero",
    class: "carousel-item",
    source: "./images/Prod9.png",
    altText: "Guacal",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Grabado en plastico",
    description: "Grabado laser",
    class: "carousel-item",
    source: "./images/Prod10.png",
    altText: "Grabado en plastico",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Grabado en acero",
    description: "Grabado laser",
    class: "carousel-item",
    source: "./images/Prod11.png",
    altText: "Grabado en acero",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Casa de pájaro",
    description: "Quemada e impregnada con protección para intemperie",
    class: "carousel-item",
    source: "./images/Prod12.png",
    altText: "Casa de pájaro",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Reloj",
    description: "Grabado y corte laser",
    class: "carousel-item",
    source: "./images/Prod13.png",
    altText: "Reloj",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Servilletero",
    description: "Impregnado con aceite mineral",
    class: "carousel-item",
    source: "./images/Prod14.png",
    altText: "Servilletero",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Porta botella para muro",
    description: "Base de bambú",
    class: "carousel-item",
    source: "./images/Prod15.png",
    altText: "Porta botella para muro",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Soporte de guitarra",
    description: "Para muro",
    class: "carousel-item",
    source: "./images/Prod16.png",
    altText: "Soporte de guitarra",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Soporte de guitarra",
    description: "Para muro",
    class: "carousel-item",
    source: "./images/Prod17.png",
    altText: "Soporte de guitarra",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
];

export default imgArray;
