const imgArray = [
  {
    name: "El taller",
    description: "Imaginando cosas útiles!",
    class: "carousel-item active",
    source: "./images/Banner.jpg",
    altText: "WorkShop",
    buttonClass: "active",
    buttonAriaCurrent: 'aria-current="true"',
  },

  {
    name: "Maceteros",
    description: "Impregnados con aceite mineral",
    class: "carousel-item",
    source: "./images/prod1.jpg",
    altText: "Macetero",
    buttonClass: "",
    buttonAriaCurrent: "",
  },

  {
    name: "Porta vaso con Código QR",
    description: "Grabado y corte laser",
    class: "carousel-item",
    source: "./images/prod2.jpg",
    altText: "Porta vasos",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Porta vaso Logotipo",
    description: "Grabado y corte laser",
    class: "carousel-item",
    source: "./images/prod3.jpg",
    altText: "Porta vaso",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Porta cepillos",
    description: "Impregnado de aceite mineral",
    class: "carousel-item",
    source: "./images/prod4.jpg",
    altText: "Porta cepillos",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Porta cepillos",
    description: "Impregnado de aceite mineral",
    class: "carousel-item",
    source: "./images/prod5.jpg",
    altText: "Porta cepillos",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Desayunador",
    description: "Superficie de porcelanato, canteado de bambú",
    class: "carousel-item",
    source: "./images/prod6.jpg",
    altText: "Desayunador",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Lapicero",
    description: "Con huella de perrito",
    class: "carousel-item",
    source: "./images/prod7.jpg",
    altText: "Lapicero",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Guacal",
    description: "Almacenamiento diverso con agarraderas de cuero",
    class: "carousel-item",
    source: "./images/prod8.jpg",
    altText: "Guacal",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Guacal",
    description: "Almacenamiento diverso con agarraderas de cuero",
    class: "carousel-item",
    source: "./images/prod9.jpg",
    altText: "Guacal",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Grabado en plastico",
    description: "Grabado laser",
    class: "carousel-item",
    source: "./images/prod10.jpg",
    altText: "Grabado en plastico",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Grabado en acero",
    description: "Grabado laser",
    class: "carousel-item",
    source: "./images/prod11.jpg",
    altText: "Grabado en acero",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Casa de pájaro",
    description: "Quemada e impregnada con protección para intemperie",
    class: "carousel-item",
    source: "./images/prod12.jpg",
    altText: "Casa de pájaro",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Reloj",
    description: "Grabado y corte laser",
    class: "carousel-item",
    source: "./images/prod13.jpg",
    altText: "Reloj",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Servilletero",
    description: "Impregnado con aceite mineral",
    class: "carousel-item",
    source: "./images/prod14.jpg",
    altText: "Servilletero",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Porta botella para muro",
    description: "Base de bambú",
    class: "carousel-item",
    source: "./images/prod15.jpg",
    altText: "Porta botella para muro",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Soporte de guitarra",
    description: "Para muro",
    class: "carousel-item",
    source: "./images/prod16.jpg",
    altText: "Soporte de guitarra",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
  {
    name: "Soporte de guitarra",
    description: "Para muro",
    class: "carousel-item",
    source: "./images/prod17.jpg",
    altText: "Soporte de guitarra",
    buttonClass: "",
    buttonAriaCurrent: "",
  },
];

export default imgArray;
